### PR TITLE
Update `equals()` in `ModelManager` and fix integration tests that were affected

### LINKED ISSUE #199: Update `equals()` method of `ModelManager` to check for equality of newly added fields
Currently, the `equals()` method only checks for equality of the following fields:
- `addressBook`
- `userPref`
- `filteredClients`

The following fields have been added to `ModelManager`:
- `clients`
- `visibleRentalInformationList`
- `lastViewedClient`
- `commandHistoryStorage`

However, the `equals()` method has not been updated to check for equality of the three newly added fields.

I.e. This has to be done:
```java
return addressBook.equals(otherModelManager.addressBook)
                && userPrefs.equals(otherModelManager.userPrefs)
                && filteredClients.equals(otherModelManager.filteredClients)
                && clients.equals(otherModelManager.clients)
                && visibleRentalInformationList.equals(otherModelManager.visibleRentalInformationList)
                && lastViewedClient.equals(otherModelManager.lastViewedClient)
                && commandHistoryStorage.equals(otherModelManager.commandHistoryStorage);
```

This causes quite a number of tests to fail, thus these tests will have to be investigated and amended as well.

### PR DESCRIPTION
**Pull request by zackjh**
Resolves #199 

- The changes to `equals()` in `ModelManager` caused integration tests in `DeleteRentalCommandTest.java` and `EditRentalCommandTest.java` to fail.
  - This was because the `lastViewedClient` and `visibleRentalInformationList` fields of `expectedModel` were not updated.
  - The behavior of `expectedModel` in certain tests within `DeleteRentalCommandTest.java` and `EditRentalCommandTest.java` has been updated to fix this issue.
    - See commits 65e60ca700a60f3e5db9ad8d2b093e3628efb8b6 and 399d117d5c9f4d017c14906569d987cbe30c7df2 for more details.

- Implemented `equals()` in `CommandHistoryStorage` as it is required for `equals()` in `ModelManager`.
  - See commit 30ba69a84a4821a9de1310483f51c9131dfecddf for more details.

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -210,7 +211,11 @@ public boolean equals(Object other) {
         ModelManager otherModelManager = (ModelManager) other;
         return addressBook.equals(otherModelManager.addressBook)
                 && userPrefs.equals(otherModelManager.userPrefs)
-                && clients.equals(otherModelManager.clients);
+                && filteredClients.equals(otherModelManager.filteredClients)
+                && clients.equals(otherModelManager.clients)
+                && visibleRentalInformationList.equals(otherModelManager.visibleRentalInformationList)
+                && Objects.equals(lastViewedClient.get(), otherModelManager.lastViewedClient.get())
+                && commandHistoryStorage.equals(otherModelManager.commandHistoryStorage);
```
Comment (gohsl99) [inline src/main/java/seedu/address/model/ModelManager.java:218]: Please add tests for the new equals method, should be quite straight forward.

File: src/main/java/seedu/address/storage/CommandHistoryStorage.java [hunk 2]
```diff
@@ -187,4 +187,19 @@ public static void initHistory() {
...
+        if (!(obj instanceof CommandHistoryStorage)) {
+            return false;
+        }
+        CommandHistoryStorage other = (CommandHistoryStorage) obj;
+
+        return commandHistoryFilePath.equals(other.commandHistoryFilePath)
+                && lines.equals(other.lines)
+                && currentLineNumber == other.currentLineNumber
+                && previousTotalLines == other.previousTotalLines;
+    }
```
Comment (gohsl99) [inline src/main/java/seedu/address/storage/CommandHistoryStorage.java:204]: Same apply to this equals method.

File: src/main/java/seedu/address/model/ModelManager.java (hunk 1 above)
Comment (zackjh) [reply src/main/java/seedu/address/model/ModelManager.java:218]: Implementing tests for the new `equals()` method is more complicated than expected because it would require refactoring of the way that `ModelManagerTest.java` sets up its tests.

I suggest I create a new issue for refactoring `ModelManagerTest.java` and address it in v1.6.

File: src/main/java/seedu/address/storage/CommandHistoryStorage.java (hunk 2 above)
Comment (zackjh) [reply src/main/java/seedu/address/storage/CommandHistoryStorage.java]: `CommandHistoryStorageTest.java` now includes test for the `equals()` method.

See commit b5d203f1110644d35c2fffdfe7694b6168979f2f for more details.
