### PR TITLE
Fix command format and some alpha bugs

### LINKED ISSUE #194: Standardize command format in help message
The command format in help message should aligned with the one in UG.

### LINKED ISSUE #197: Customer List of Rental Information is Being Saved Incorrectly on Exit
The `customerList` field of rental information is saved with extra enclosing square brackets on app exit is the `rview` command is run on the client. This causes the UI to incorrectly display the customer list.

---

image

---

**State of `data/addressbook.json`**

Before exiting:
```json
{
  "clients" : [ {
    "name" : "John Doe",
    "phone" : "98765432",
    "email" : "johnd@example.com",
    "tags" : [ "owesMoney", "friends" ],
    "rentalInformationList" : [ {
      "address" : "BLK 1 Bishan",
      "rentalStartDate" : "01/01/2024",
      "rentalEndDate" : "31/12/2024",
      "rentDueDate" : "15",
      "monthlyRent" : "2700.00",
      "deposit" : "8100.00",
      "customerList" : "[Steven, David]"
    } ]
  }, {
    "name" : "Bernice Yu",
    "phone" : "12345789",
    "email" : "berniceyu@example.com",
    "tags" : [ "colleagues", "friends" ],
    "rentalInformationList" : [ ]
  } ]
}
```

After running `rview 1` then exiting:
```json
{
  "clients" : [ {
    "name" : "John Doe",
    "phone" : "98765432",
    "email" : "johnd@example.com",
    "tags" : [ "owesMoney", "friends" ],
    "rentalInformationList" : [ {
      "address" : "BLK 1 Bishan",
      "rentalStartDate" : "01/01/2024",
      "rentalEndDate" : "31/12/2024",
      "rentDueDate" : "15",
      "monthlyRent" : "2700.00",
      "deposit" : "8100.00",
      "customerList" : "[[Steven, David]]"
    } ]
  }, {
    "name" : "Bernice Yu",
    "phone" : "12345789",
    "email" : "berniceyu@example.com",
    "tags" : [ "colleagues", "friends" ],
    "rentalInformationList" : [ ]
  } ]
}
```

### LINKED ISSUE #198: Fix redit not editing other fields

### LINKED ISSUE #200: Fix redit not detecting duplicate address

### PR DESCRIPTION
**Pull request by gohsl99**
Fixes #194, Fixes #197, Fixes #198, Fixes #200

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditRentalCommand.java [hunk 1]
```diff
@@ -47,14 +47,14 @@ public class EditRentalCommand extends Command {
...
             + "Existing values will be overwritten by the input values.\n"
             + "Parameters: CLIENT_INDEX (must be a positive integer) "
-            + "[" + PREFIX_RENTAL_INDEX + " RENTAL_INDEX (must be a positive integer)] "
+            + PREFIX_RENTAL_INDEX + " RENTAL_INDEX (must be a positive integer) "
             + "[" + PREFIX_ADDRESS + "ADDRESS] "
-            + "[" + PREFIX_RENTAL_START_DATE + "RENTAL START DATE] "
-            + "[" + PREFIX_RENTAL_END_DATE + "RENTAL END DATE] "
-            + "[" + PREFIX_RENT_DUE_DATE + "RENT DUE DATE] "
-            + "[" + PREFIX_MONTHLY_RENT + "MONTHLY RENT] "
+            + "[" + PREFIX_RENTAL_START_DATE + "RENTAL_START_DATE] "
```
Comment (winstonlimjy) [inline src/main/java/seedu/address/logic/commands/EditRentalCommand.java:52]: Good renaming.

File: src/main/java/seedu/address/model/rentalinformation/MonthlyRent.java [hunk 2]
```diff
@@ -45,7 +45,7 @@ public static boolean isValidMonthlyRent(String test) {
 
     @Override
     public String toString() {
-        return monthlyRent == null ? "null" : Double.toString(monthlyRent);
+        return monthlyRent == null ? "null" : String.format("$%.2f", monthlyRent);
```
Comment (winstonlimjy) [inline src/main/java/seedu/address/model/rentalinformation/MonthlyRent.java:48]: Good job spotting and fixing the bug
